// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIPQYQmcOotNY7o6gtXNi4mkPbU-1zF-I',
    appId: '1:1084392030643:web:9032fbaafe39f0b8f90bc6',
    messagingSenderId: '1084392030643',
    projectId: 'mynews-9f7b2',
    authDomain: 'mynews-9f7b2.firebaseapp.com',
    storageBucket: 'mynews-9f7b2.appspot.com',
    measurementId: 'G-CK60VX0V00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdmE66HPOPiLDjSKb5D6juBiPUNGB-H5Q',
    appId: '1:1084392030643:android:a57914ce0d75fdf2f90bc6',
    messagingSenderId: '1084392030643',
    projectId: 'mynews-9f7b2',
    storageBucket: 'mynews-9f7b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGWJAfVH7vepvg_CgGexizLxt0O0u9iBc',
    appId: '1:1084392030643:ios:07016136338c4911f90bc6',
    messagingSenderId: '1084392030643',
    projectId: 'mynews-9f7b2',
    storageBucket: 'mynews-9f7b2.appspot.com',
    iosBundleId: 'com.example.myNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGWJAfVH7vepvg_CgGexizLxt0O0u9iBc',
    appId: '1:1084392030643:ios:07016136338c4911f90bc6',
    messagingSenderId: '1084392030643',
    projectId: 'mynews-9f7b2',
    storageBucket: 'mynews-9f7b2.appspot.com',
    iosBundleId: 'com.example.myNews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIPQYQmcOotNY7o6gtXNi4mkPbU-1zF-I',
    appId: '1:1084392030643:web:da4b1e2d971c441af90bc6',
    messagingSenderId: '1084392030643',
    projectId: 'mynews-9f7b2',
    authDomain: 'mynews-9f7b2.firebaseapp.com',
    storageBucket: 'mynews-9f7b2.appspot.com',
    measurementId: 'G-F0DV27Z1D0',
  );
}
